import pickle
import features
import matplotlib.pyplot as plt

data_input = open('png/1001/people.pkl','rb')
data = pickle.load(data_input)
data_input.close()
'''
zhifangtu = features.zhifangtu(data)
print('zhifangtu:', zhifangtu)
fangcha = features.fangcha(data)
print('fangcha:', fangcha)
piandu = features.piandu(data)
print('piandu:', piandu)
fengdu = features.fengdu(data)
print('fengdu:', fengdu)
junyunxing = features.junyunxing(data)
print('junyunxing:', junyunxing)
shang = features.shang(data)
print('shang:', shang)
tiji = features.tiji(data)
print('tiji:', tiji)
CTqujian = features.CTqujian(data)
# print('CTqujian:', CTqujian)
GLCM = features.GLCM(data)
# print('GLCM:', GLCM)
zixiangguan = features.zixiangguan(data, GLCM)
print('zixiangguan:', zixiangguan)
jiquanqushi = features.jiquanqushi(data, GLCM)
print('jiquanqushi:', jiquanqushi)
cuzhuangtuqi = features.cuzhuangtuqi(data, GLCM)
print('cuzhuangtuqi:', cuzhuangtuqi)
GLCMjunyunxing = features.GLCMjunyunxing(data, GLCM)
print('GLCMjunyunxing:', GLCMjunyunxing)
GLCMshang = features.GLCMshang(data, GLCM)
print('GLCMshang:', GLCMshang)
IMC1 = features.IMC1(data, GLCM)
print('IMC1:', IMC1)
GLRL = features.GLRL(data)
# print('GLRL:', GLRL)
SRE = features.SRE(data, GLRL)
print('SRE:', SRE)
LRE = features.LRE(data, GLRL)
print('LRE:', LRE)
LGLRE = features.LGLRE(data, GLRL)
print('LGLRE:', LGLRE)
HGLRE = features.HGLRE(data, GLRL)
print('HGLRE:', HGLRE)
GLN = features.GLN(data, GLRL)
print('GLN:', GLN)
RLN = features.RLN(data, GLRL)
print('RLN:', RLN)
RP = features.RP(data, GLRL)
print('RP:', RP)
'''
a = min(zhifangtu); b = max(zhifangtu)
after = []
for i in range(512):
    temp = (zhifangtu[i] - a)/(b - a)
    after.append(temp)
OK = []
for i in range(20):
    OK.append(after)

plt.figure()
plt.imshow(OK)
plt.show()